title: The Simpler, The Better
author: Gunwoo Park (Iwan)
description: Life is a process of failing gracefully. Based!
linkedin_username: iwanpark

# Build settings
theme: minima
plugins:
  - jekyll-feed
